version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mysql
  mongo:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'